#pragma config(Sensor, S1,     leftLight,      sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S2,     ultraSonic,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S4,     rightLight,     sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorA,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorD,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float speed = 100;
int fullSpeed = 0;
int stop = 0;

void moveForward(float left, float right) {
	setMotorSpeed(leftMotor, left);
	setMotorSpeed(rightMotor, right);
}

task main()
{
	while(true) {
		/*if (getColorName(S4) == colorBlack) {
			playTone(784, 15);
			delay(1000);
		} */
		if (getUSDistance(ultraSonic) < 90 && getUSDistance(ultraSonic) > 6) {
			moveForward(speed, speed);
		//setMotorSync(leftMotor, rightMotor, 0, speed);
		wait1Msec(100);
		speed -= 2.7;

		}

		if(speed < 0) {
			speed = 0;
			moveForward(speed, speed);
		wait1Msec(2000);
	}
		/*
		else {
			//moveForward(50 * getUSDistance(ultraSonic))
		speed = 0;
		setMotorSync(leftMotor, rightMotor, 0, speed);
		wait1Msec(2000);
		}
		//setMotorSync(leftMotor,rightMotor, 0, 50);*/
	}
}
