#pragma config(Sensor, S1,     leftLight,      sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S2,     ultraSonic,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S4,     rightLight,     sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorA,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorD,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int speed = 60;
int fullSpeed = 0;
int stoppeds = 0;

void moveForward(int left, int right) {
	setMotorSpeed(leftMotor, left);
	setMotorSpeed(rightMotor, right);
}

task detect() {
		while(true) {
		/*if (getColorName(S4) == colorBlack) {
			playTone(784, 15);
			delay(1000);
		} */
		int distance = getUSDistance(ultraSonic);
		displayBigTextLine(3, "%d", distance);
		displayBigTextLine(5, "%d", speed);
		
		moveForward(70, 70);
		
		//check if the obstacle is in the range of detection
		if(distance < 90) {
			if(distance > 70) {
				speed = 50;
				moveForward(speed, speed);
				wait1Msec(400);
			}else if(distance > 50){
				speed = 40;
				moveForward(speed, speed);
				wait1Msec(400);
			}else if(distance > 30) {
				speed = 25;
				moveForward(speed, speed);
				wait1Msec(400);
			}else if (distance > 23) {
				speed = 15;
				moveForward(speed, speed);
				wait1Msec(400);
			}else if (distance > 10) {
				speed = 10;
				moveForward(speed, speed);
				wait1Msec(400);
			} else {
				moveForward(0, 0);
				wait1Msec(2000);
			}
			//wait1Msec(400);
		}else{
			
		
		}
		
		
		
		
		
		
	/*	
		
		if (distance < 90 && stoppeds == 0) {
			moveForward(speed, speed);
		//setMotorSync(leftMotor, rightMotor, 0, speed);
		wait1Msec(100);
		speed -= 1;
		
				if( getUSDistance(ultraSonic) < 10 && stoppeds == 0) {
					speed = 0;
					moveForward(speed, speed);
					stoppeds = 1;
				wait1Msec(2000);
			}
			
			
			
			
			
		}

		
		
		else {
			//moveForward(50 * getUSDistance(ultraSonic))
		speed = 0;
		setMotorSync(leftMotor, rightMotor, 0, speed);
		wait1Msec(2000);
		}
		//setMotorSync(leftMotor,rightMotor, 0, 50);*/
	}
}

task main()
{
	startTask(detect);
	while(true) {
	
	}
}
